/* Generated by cbindgen from loro-c-api. DO NOT EDIT BY HAND.
   Regenerate with the CMake `regenerate-header` target. */

#ifndef LORO_LORO_H
#define LORO_LORO_H



#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/**
 * Status / error code returned by fallible `loro-c-api` functions.
 *
 * `LORO_OK` is guaranteed to be `0`, so callers may treat any non-zero value as failure.
 */
typedef enum LoroStatus {
    /**
     * Success.
     */
    LORO_OK = 0,
    /**
     * A pointer argument was null, an index was out of bounds, or an argument was
     * otherwise invalid.
     */
    LORO_ERR_INVALID_ARG = 1,
    /**
     * A requested container, version, or id could not be found.
     */
    LORO_ERR_NOT_FOUND = 2,
    /**
     * Failed to decode/import binary data (corruption, version mismatch, ...).
     */
    LORO_ERR_DECODE = 3,
    /**
     * Failed to encode/export.
     */
    LORO_ERR_ENCODE = 4,
    /**
     * A string argument was not valid UTF-8.
     */
    LORO_ERR_UTF8 = 5,
    /**
     * A Rust panic was caught at the FFI boundary.
     */
    LORO_ERR_PANIC = 6,
    /**
     * Any other error reported by the underlying loro library.
     */
    LORO_ERR_OTHER = 7,
} LoroStatus;

/**
 * Opaque handle to a Loro document. Create with [`loro_doc_new`], release with
 * [`loro_doc_free`].
 */
typedef struct LoroDoc LoroDoc;

/**
 * Opaque handle to a Loro text container.
 */
typedef struct LoroText LoroText;

/**
 * An owned, heap-allocated byte buffer handed to the caller.
 *
 * Free it exactly once with [`loro_bytes_free`]. `data` may be null only when `len`
 * and `cap` are both `0` (an empty buffer); in that case `loro_bytes_free` is a no-op.
 */
typedef struct LoroBytes {
    /**
     * Pointer to the bytes. Owned by the buffer; freed by `loro_bytes_free`.
     */
    uint8_t *data;
    /**
     * Number of valid bytes in `data`.
     */
    uintptr_t len;
    /**
     * Allocation capacity backing `data` (needed to reconstruct the Rust `Vec`).
     */
    uintptr_t cap;
} LoroBytes;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the version of the underlying `loro` Rust crate as a static,
 * nul-terminated C string. The returned pointer is valid for the lifetime of the
 * program and must NOT be freed.
 */
const char *loro_version(void);

/**
 * Frees a text handle. Passing null is a no-op. Safe to call before or after the
 * originating `LoroDoc*` is freed.
 */
void loro_text_free(struct LoroText *text);

/**
 * Inserts the UTF-8 string `(s, len)` at Unicode codepoint index `pos`.
 */
enum LoroStatus loro_text_insert(struct LoroText *text,
                                 uintptr_t pos,
                                 const char *s,
                                 uintptr_t len);

/**
 * Inserts the UTF-8 string `(s, len)` at UTF-8 byte index `pos`.
 */
enum LoroStatus loro_text_insert_utf8(struct LoroText *text,
                                      uintptr_t pos,
                                      const char *s,
                                      uintptr_t len);

/**
 * Deletes `len` Unicode codepoints starting at codepoint index `pos`.
 */
enum LoroStatus loro_text_delete(struct LoroText *text, uintptr_t pos, uintptr_t len);

/**
 * Deletes `len` UTF-8 bytes starting at byte index `pos`.
 */
enum LoroStatus loro_text_delete_utf8(struct LoroText *text, uintptr_t pos, uintptr_t len);

/**
 * Returns the length of the text in Unicode codepoints. Returns 0 on a null handle.
 */
uintptr_t loro_text_len_unicode(const struct LoroText *text);

/**
 * Returns the length of the text in UTF-8 bytes. Returns 0 on a null handle.
 */
uintptr_t loro_text_len_utf8(const struct LoroText *text);

/**
 * Returns `true` if the text is empty (also returns `true`, with an error recorded, on
 * a null handle).
 */
bool loro_text_is_empty(const struct LoroText *text);

/**
 * Writes the text's current content as UTF-8 bytes (NOT nul-terminated; use `len`) into
 * `*out`. `*out` is only written on `LORO_OK`; free it with `loro_bytes_free`.
 */
enum LoroStatus loro_text_to_string(const struct LoroText *text, struct LoroBytes *out);

/**
 * Creates a new, empty document. Never returns null except on allocation failure /
 * caught panic. Release with [`loro_doc_free`].
 */
struct LoroDoc *loro_doc_new(void);

/**
 * Frees a document handle. Passing null is a no-op.
 *
 * Container handles (e.g. `LoroText*`) obtained from this document are strong
 * co-owners of the underlying document state and remain valid after the `LoroDoc*`
 * is freed — they may be freed in any order. See `loro.h`/`loro.hpp` for details.
 */
void loro_doc_free(struct LoroDoc *doc);

/**
 * Creates a deep fork of the document at its current version. Returns a new owned
 * handle, or null on error. Release with [`loro_doc_free`].
 */
struct LoroDoc *loro_doc_fork(const struct LoroDoc *doc);

/**
 * Commits the pending operations into the oplog, making them exportable and triggering
 * any subscriptions.
 */
enum LoroStatus loro_doc_commit(struct LoroDoc *doc);

/**
 * Returns the document's current peer id. Returns 0 on a null handle.
 */
uint64_t loro_doc_peer_id(const struct LoroDoc *doc);

/**
 * Sets the document's peer id. Fails if there are uncommitted local changes under the
 * previous peer id.
 */
enum LoroStatus loro_doc_set_peer_id(struct LoroDoc *doc, uint64_t peer);

/**
 * Returns the root text container named `(id, id_len)` (UTF-8, not nul-terminated),
 * creating it if it does not yet exist. Returns null on error. Release the returned
 * handle with `loro_text_free`.
 */
struct LoroText *loro_doc_get_text(const struct LoroDoc *doc, const char *id, uintptr_t id_len);

/**
 * Exports a full snapshot (complete history + current state) into `*out`.
 * `*out` is only written on `LORO_OK`; free it with `loro_bytes_free`.
 */
enum LoroStatus loro_doc_export_snapshot(const struct LoroDoc *doc, struct LoroBytes *out);

/**
 * Exports all updates (the complete operation history, no state snapshot) into `*out`.
 * `*out` is only written on `LORO_OK`; free it with `loro_bytes_free`.
 */
enum LoroStatus loro_doc_export_updates(const struct LoroDoc *doc, struct LoroBytes *out);

/**
 * Imports a snapshot or updates blob `(data, len)` produced by an export function,
 * merging it into the document.
 */
enum LoroStatus loro_doc_import(struct LoroDoc *doc, const uint8_t *data, uintptr_t len);

/**
 * Serializes the entire document state (resolving nested containers) to JSON bytes into
 * `*out`. `*out` is only written on `LORO_OK`; free it with `loro_bytes_free`.
 */
enum LoroStatus loro_doc_get_deep_value_json(const struct LoroDoc *doc, struct LoroBytes *out);

/**
 * Returns a pointer to the current thread's last-error message as a nul-terminated C
 * string, or `NULL` if no error has been recorded on this thread.
 *
 * The returned pointer is owned by the library and is valid only until the next
 * `loro-c-api` call that records an error on the same thread. Do NOT free it. Copy the
 * string if you need to keep it.
 */
const char *loro_last_error_message(void);

/**
 * Frees a [`LoroBytes`] previously returned by this library. Passing an
 * all-zero/empty buffer is a no-op. Must be called at most once per buffer.
 */
void loro_bytes_free(struct LoroBytes bytes);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* LORO_LORO_H */
